spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: pass
  h2: # localhost:<port>/h2-console
    console:
      enabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO